name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
env:
  VITE_FIREBASE_APIKEY: ${{ secrets.VITE_FIREBASE_APIKEY }}
  VITE_FIREBASE_AUTHDOMAIN: ${{ secrets.VITE_FIREBASE_AUTHDOMAIN }}
  VITE_FIREBASE_PROJECTID: ${{ secrets.VITE_FIREBASE_PROJECTID }}
  VITE_FIREBASE_STORAGEBUCKET: ${{ secrets.VITE_FIREBASE_STORAGEBUCKET }}
  VITE_FIREBASE_MESSAGINGSENDERID: ${{ secrets.VITE_APP_FIREBASE_MESSAGINGSENDERID }}
  VITE_FIREBASE_MEASUREMENTID: ${{ secrets.VITE_FIREBASE_MEASUREMENTID }}
  VITE_FIREBASE_APIID: ${{ secrets.VITE_FIREBASE_APIID }}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['>=16.15.1']
    steps:
      - uses: actions/checkout@v2

      - name: Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn

      - name: Build app
        run: yarn build
    
      - name: Firebase deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_VUE_POKE_APP }}'
          channelId: live
          projectId: vue-poke-app
