name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
env:
  VUE_APP_FIREBASE_APIKEY: ${{ secrets.VUE_APP_FIREBASE_APIKEY }}
  VUE_APP_FIREBASE_AUTHDOMAIN: ${{ secrets.VUE_APP_FIREBASE_AUTHDOMAIN }}
  VUE_APP_FIREBASE_PROJECTID: ${{ secrets.VUE_APP_FIREBASE_PROJECTID }}
  VUE_APP_FIREBASE_STORAGEBUCKET: ${{ secrets.VUE_APP_FIREBASE_STORAGEBUCKET }}
  VUE_APP_FIREBASE_MESSAGINGSENDERID: ${{ secrets.VUE_APP_FIREBASE_MESSAGINGSENDERID }}
  VUE_APP_FIREBASE_MEASUREMENTID: ${{ secrets.VUE_APP_FIREBASE_MEASUREMENTID }}
  VUE_APP_FIREBASE_APIID: ${{ secrets.VUE_APP_FIREBASE_APIID }}
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  
      - name: Install dependencies
        run: npm i

      - name: Build app
        run: npm run build
    
      - name: Firebase deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_VUE_POKE_APP }}'
          channelId: live
          projectId: vue-poke-app
